name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
        
    - name: env
      run: |
        sudo apt-get install tar zip -y
        
    - name: Build
      run: | 
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o darwin-amd64-EmergencyTool main.go
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o linux-amd64-EmergencyTool main.go
        CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o freebsd-amd64-EmergencyTool main.go
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o windows-amd64-EmergencyTool main.go
        CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o windows-386-EmergencyTool main.go
        tar -cvf darwin-amd64-EmergencyTool.tar darwin-amd64-EmergencyTool config/config.txt
        tar -cvf linux-amd64-EmergencyTool.tar linux-amd64-EmergencyTool config/config.txt
        tar -cvf freebsd-amd64-EmergencyTool.tar freebsd-amd64-EmergencyTool config/config.txt
        zip windows-amd64-EmergencyTool.zip windows-amd64-EmergencyTool config/config.txt
        zip windows-386-EmergencyTool.zip windows-amd64-EmergencyTool config/config.txt

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          darwin-amd64-EmergencyTool.tar
          linux-amd64-EmergencyTool.tar
          freebsd-amd64-EmergencyTool.tar
          windows-amd64-EmergencyTool.zip
          windows-386-EmergencyTool.zip
        tag_name: 2.3
